@baseUrl = http://localhost:8000/api
@token = 13|pRpy4kZpamKy4MsX6CaJy0n2HRnmVRrUTCH8jpqUc5cc083c


### 🧾 Obtener ventas (requiere token)
GET {{baseUrl}}/sales
Authorization: Bearer {{token}}


### ❌ Cancelar venta
POST {{baseUrl}}/sales/1/cancel
Authorization: Bearer {{token}}


### ↩️ Revertir venta
POST {{baseUrl}}/sales/1/revert
Authorization: Bearer {{token}}


### 📦 Obtener ajustes de inventario
GET {{baseUrl}}/inventory-adjustments
Authorization: Bearer {{token}}


### ➕ Crear un ajuste de inventario
POST {{baseUrl}}/inventory-adjustments
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "product_id": 8,
  "quantity": 45,
  "adjustment_type": "addition",
  "reason": "Reposición de stock"
}


### 🔍 Obtener un ajuste por ID
GET {{baseUrl}}/inventory-adjustments/16
Authorization: Bearer {{token}}


### ✏️ Actualizar un ajuste
PUT {{baseUrl}}/inventory-adjustments/16
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "product_id": 8,
  "quantity": 3,
  "adjustment_type": "subtraction",
  "reason": "Corrección de inventario"
}


### 🗑️ Eliminar un ajuste
DELETE {{baseUrl}}/inventory-adjustments/16
Authorization: Bearer {{token}}

### 🔐 Login (para obtener token)
POST {{baseUrl}}/login
Content-Type: application/json

{
  "email": "yahir@gmail.com",
  "password": "12345"
}


### 📋 Obtener todos los roles
GET {{baseUrl}}/roles
Authorization: Bearer {{token}}


### ➕ Crear un rol
POST {{baseUrl}}/roles
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "name": "Supervisor",
  "description": "Encargado de supervisar operaciones"
}



### ✏️ Actualizar un rol
PUT {{baseUrl}}/roles/4
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "name": "barredor",
  "description": "Acceso total al sistema"
}


### 🗑️ Eliminar un rol
DELETE {{baseUrl}}/roles/4
Authorization: Bearer {{token}}